site_name: Iridescent的cs笔记本
site_url: https://lhxcs.github.io/
repo_name: lhxcs/note
repo_url: https://github.com/lhxcs/note/
edit_uri: tree/master/docs
site_description: lhx的笔记本
copyright: Copyright &copy; 2022-2023 <a href="https://github.com/lhxcs" target="_blank" rel="noopener">Iridescent</a>

theme: 
  name: 'material'
  custom_dir: overrides
  language: 'zh'
  icon: 
    logo: material/notebook-outline
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
  font: false
  palette:
      - scheme: default
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
    # - scheme: default
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
    - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - css/custom.css
    - css/counter.css

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    # - js/scheme.js
    - js/katex.js

plugins:
  - search
  - statistics
  - changelog
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md

nav:
  - Home: 
    - index.md
    - 更新记录: changelog.md
  - Computer Science:
    - cs/index.md
    - 编程语言:
      - cs/language/index.md
      - Python: cs/language/python.md
      - C: cs//language/c/c.md
    - 离散数学理论基础: cs/dm.md
    - 数据结构基础:
      - cs/ds/index.md
      - Algorithm Analysis: cs/ds/ch1.md
      - 树: cs/ds/ch4.md
      - 堆: cs/ds/ch5.md
      - 理论题: cs/ds/pta.md
      - code: cs/ds/tree.md
    - 计算机逻辑设计基础:
      - cs/CLDF/index.md
      - Chapter1 Digital Systems and Information: cs/CLDF/lec1.md
      - Chapter2 Combinational Logic Circuits: cs/CLDF/lec2.md
      - Chapter3 Combinational Logic Design: cs/CLDF/lec3.md
      - Chapter4 Sequential Circuits: cs/CLDF/lec4.md
      - Chapter6 Registers and Register Transfers: cs/CLDF/lec6.md
    - 优化基本理论与方法:
      - cs/opt/index.md
      - Lec1 Introduction: cs/opt/lec1.md
  - AI:
    - Computer Vision:
      - Stanford:CS231n:
        - AI/cv/cs231n/index.md
        - Lec2 Image Classification: AI/cv/cs231n/lec2.md
        - Lec3 Regularization and Optimization: AI/cv/cs231n/lec3.md
        - Lec4 Neural Networks and Backpropagation: AI/cv/cs231n/lec4.md
        - Lec5 Image Classification with CNNs: AI/cv/cs231n/lec5.md
        - Lec6 Training Neural Networks(I): AI/cv/cs231n/lec6.md
        - Lec7 Training Neural Networks(II): AI/cv/cs231n/lec7.md
        - Lec8 Deep Learning Frameworks: AI/cv/cs231n/lec8.md
      - ZJU:计算机视觉导论:
        - AI/cv/icv/index.md
        - Lec1 Introduction: AI/cv/icv/lec1.md
        - Lec2 Image Formation: AI/cv/icv/lec2.md
        - Lec3 Image Processing: AI/cv/icv/lec3.md
        - Lec4 Model Fitting and Optimization: AI/cv/icv/lec4.md
        - Lec5 Image Matching and Motion Estimation: AI/cv/icv/lec5.md
        - Lec6 Image Stitching: AI/cv/icv/lec6.md
        - Lec7 Structure from Motion: AI/cv/icv/lec7.md
        - Lec8 Depth Estimation and 3D Reconstruction: AI/cv/icv/lec8.md
        - Lec10 Image Segmentation: AI/cv/icv/lec10.md
        - Project Related: AI/cv/icv/neus.md
        - COLMAP: AI/cv/icv/COLMAP.md
  - 数学基础:
    - math/index.md
    - Math for deep learning: math/mdl.md
    - 数学分析: math/analysis.md
    - 线性代数: math/algebra.md
    - 概率论: 
      - Conditional Probability, Independence, and Combinations of Events: math/probability/note14.md
      - Random Variables--Distribution and Expectation: math/probability/note15.md
      - Variance and covariance: math/probability/note16.md
  - English:
    - Reading:
      - TOFEL Reading: English/reading/reading.md 
      - Foreign Magazines: English/reading/note.md
    - Writing:
      - TOFEL Writing: English/writing/Writing.md
